language: node_js
node_js:
  - "5.8.0"
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y python-software-properties
  - sudo apt-add-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
  - sudo sed -i s/deb-src.*google.*//g /etc/apt/sources.list
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install google-chrome-stable
  - sudo chmod 1777 /dev/shm
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
  - gulp build
  - node daemon.js start
  - /home/travis/build/WandersonAlves/neweb/node_modules/protractor/bin/webdriver-manager update
script: protractor spec/conf.js
after_script:
- node daemon.js stop