language: node_js
node_js:
  - "5.8.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
  - gulp build
  - node daemon.js start
  - /home/travis/build/WandersonAlves/neweb/node_modules/protractor/bin/webdriver-manager update
script: protractor spec/conf.js
after_script:
- node daemon.js stop