language: node_js
node_js:
  - "5.8.0"
before_script:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
#  - gulp build
#  - "export DISPLAY=:99.0"
#  - sh -e /etc/init.d/xvfb start
#  - sleep 5
#  - node server.js
script: gulp build
