language: node_js
node_js:
  - "5.8.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
  - gulp build
  - node daemon.js start
  - /home/travis/build/WandersonAlves/neweb/node_modules/protractor/bin/webdriver-manager update
  - sudo apt-get -y install libxpm4 libxrender1 libgtk2.0-0 libnss3 libgconf-2-4
  - sudo apt-get -y install google-chrome-stable
  - sudo apt-get -y install xvfb gtk2-engines-pixbuf
  - sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
script: protractor spec/conf.js
after_script:
- node daemon.js stop