sudo: required
dist: trusty
language: node_js
node_js:
  - "4.2"
branches:
  only:
  - master
addons:
  apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
  - gulp build
  - node daemon.js start
  - sleep 1
  - /home/travis/build/WandersonAlves/neweb/node_modules/protractor/bin/webdriver-manager update
script: 
  - protractor spec/web-conf.js
  - protractor spec/mobile-conf.js
after_script:
  - node daemon.js stop